### ISSUE TITLE
[Proposal] Publish an architecture-independent `websockets-11.0-none-any.whl`

### ISSUE THREAD

**Issue by Atokulus** [aaugustin/websockets#1300]
Dear community
I hope this finds you well 😄

I currently write a Python application on an ARMv7-based IoT computer running Linux. As the `websockets` package is only providing wheels for major architectures and platforms (such ARM64, x86-x64, etc.), it would be really great if you could provide a `websockets-11.0-py37.py38.py39.py310.py311-none-any.whl` on PyPi as well (without the `speedups.c` extension).

I currently build and use the pure Python wheel on my own. Nevertheless it would be great for other people, to have support for some more exotic or industrial platforms and not have to take the same steps I had to take. As websockets are more and more common in these fields, I also see quite some adoption.

Tell me what you think 😉

Best regards
Markus

**Comment by aaugustin** [comment]
Do you know if cibuildwheel can be configured to produce such wheels? That would be the easiest.

A quick search doesn't yield useful results. Searching for "none-any" doesn't work well :-/

If not, what is the equivalent of https://github.com/aaugustin/websockets/blob/8e1628a14e0dd2ca98871c7500484b5d42d16b67/.github/workflows/wheels.yml#L21 to produce such wheels?

**Comment by Atokulus** [comment]
Dear @aaugustin 

Thanks for the great feedback 😄

Yes, `cibuildwheel` does not seem to support this.
I currently patch the `setup.py` to set `extensions = []` and then run `python setup.py bdist-wheel`.

Please see my flow in Gitlab CI:

```yml
stages:
  - build

build:
    stage: build
    image: python:latest
    script:
      # Install Python build dependencies
      - pip install --no-cache-dir setuptools wheel
      # Clone the original websockets code from GitHub
      - git clone https://github.com/aaugustin/websockets.git
      - cd ./websockets
      # Checkout the current release
      - git checkout tags/10.4
      # Overwrite the setup.py to remove the speedup.c extension from building and adapt version name to 10.4
      - cp -fr ../custom/websockets/setup.py ./setup.py
      # Build the architecture-independent wheel (none-any)
      - python setup.py bdist_wheel
      - cd ..
      - mkdir ./wheels
      # Copy the genererated wheel to the top-directory
      - cp ./websockets/dist/* ./wheels
      - ls ./wheels

      # Install Poetry for building my own project
      - curl -sSL https://install.python-poetry.org | python3 -
      # Building project with Poetry
      - /root/.local/bin/poetry build
      # Download all dependency wheels with architecture independent code and copy them to ./dist
      # (use websockets wheel from top-level directory via --find-links option)
      - 'pip download --verbose --platform "none-any" --find-links ./wheels --only-binary=:all: -d ./dist/wheels .'

    only:
      - master
      - staging

    # Store all the wheels from the ./dist folder as an artifact for moving them to the ARMv7 based Linux computer later.
    artifacts:
      paths:
        - ./dist/*
      expire_in: 1 week
```

And the content of the `setup.py`:

```python
# ./custom/websockets/setup.py

import pathlib
import re

import setuptools


root_dir = pathlib.Path(__file__).parent

description = "An implementation of the WebSocket Protocol (RFC 6455 & 7692)"

long_description = (root_dir / "README.rst").read_text(encoding="utf-8")

# PyPI disables the "raw" directive.
long_description = re.sub(
    r"^\.\. raw:: html.*?^(?=\w)",
    "",
    long_description,
    flags=re.DOTALL | re.MULTILINE,
)

exec((root_dir / "src" / "websockets" / "version.py").read_text(encoding="utf-8"))

packages = ["websockets", "websockets.legacy", "websockets.extensions"]

# ext_modules = [
#     setuptools.Extension(
#         "websockets.speedups",
#         sources=["src/websockets/speedups.c"],
#         optional=not (root_dir / ".cibuildwheel").exists(),
#     )
# ]

ext_modules = [] # Do not compile and include any external extension.

setuptools.setup(
    name="websockets",
    version="10.4", # Override version number
    description=description,
    long_description=long_description,
    url="https://github.com/aaugustin/websockets",
    author="Aymeric Augustin",
    author_email="aymeric.augustin@m4x.org",
    license="BSD-3-Clause",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Web Environment",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    package_dir={"": "src"},
    package_data={"websockets": ["py.typed"]},
    packages=packages,
    ext_modules=ext_modules,
    include_package_data=True,
    zip_safe=False,
    python_requires=">=3.7",
    test_loader="unittest:TestLoader",
)

```

Does this help you?

Best regards
Markus
